# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['LED_Logger.py'],
    pathex=[],
    binaries=[],
    datas=[('logo.ico', '.')],
    hiddenimports=[
        'requests',
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWebSockets',
        'PySide6.QtNetwork',
        'pysnmp',
        'pysnmp.hlapi',
        'pysnmp.hlapi.asyncio',
        'pysnmp.proto',
        'pysnmp.proto.rfc1902',
        'pyasn1',
        'pyasn1.codec.ber',
        'pyasn1.codec.ber.decoder',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='LED_Logger',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo.ico'],
)
